---

development: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  DB_FILENAME: db/local/dev.db
  SESSION_SECRET: rake new_session_secret to retrieve session secret thank you !!!!
  AWS_REGION: us-east-1
  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/994128590956/acaradar-research-interest-dev
  SQS_QUEUE_NAME: acaradar-research-interest-dev
  AWS_ACCESS_KEY_ID: <YOUR_ACCESS_KEY_ID_HERE>
  AWS_SECRET_ACCESS_KEY: <YOUR_SECRET_ACCESS_KEY_HERE>
  API_HOST: http://localhost:9292

test: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  DB_FILENAME: db/local/test.db
  SESSION_SECRET: rake new_session_secret to retrieve session secret thank you !!!!
  AWS_REGION: us-east-1
  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/994128590956/acaradar-research-interest-dev
  SQS_QUEUE_NAME: acaradar-research-interest-dev
  AWS_ACCESS_KEY_ID: <YOUR_ACCESS_KEY_ID_HERE>
  AWS_SECRET_ACCESS_KEY: <YOUR_SECRET_ACCESS_KEY_HERE>
  API_HOST: http://localhost:9292

production: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  